[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking2 = "DmafajAhpjDHyFVU2pFKSv3ZduJNCp5ba2nYjJ42pdDe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
